"""Generate the DaVinci Classic import ARXML.

There is deliberately no XML in this module.  The structure of the file - which
AUTOSAR elements exist and how they nest - lives in `templates/someip.arxml.tpl`;
the values come from `view_model.build()`.  To change the shape of the output,
edit the template, not this file.

    from arxml_gen import generate, write
    write(project, "ZA_someip.arxml")                       # default template
    write(project, "out.arxml", template="my_variant.tpl")  # another one
"""

from __future__ import annotations

import os
import sys
from typing import Optional

import licensing
import view_model
from someip_model import Project
from template_engine import Renderer, TemplateError  # noqa: F401 - re-exported

DEFAULT_TEMPLATE_NAME = "someip.arxml.tpl"


def template_dirs() -> list:
    """Where a template may live, nearest first.

    A frozen build unpacks its own copy of `templates/` into a temporary
    directory, which is thrown away on exit.  Looking beside the executable
    first lets someone drop a variant next to the .exe and use it without a
    rebuild; the bundled copy is the fallback.
    """
    if getattr(sys, "frozen", False):
        roots = [os.path.dirname(sys.executable), getattr(sys, "_MEIPASS", "")]
    else:
        roots = [os.path.dirname(os.path.abspath(__file__))]
    seen, out = set(), []
    for root in roots:
        d = os.path.join(root, "templates") if root else ""
        if d and d not in seen and os.path.isdir(d):
            seen.add(d)
            out.append(d)
    return out


TEMPLATE_DIR = (template_dirs() or [""])[0]
DEFAULT_TEMPLATE = os.path.join(TEMPLATE_DIR, DEFAULT_TEMPLATE_NAME)


def available_templates() -> list:
    """Every template on offer; a name beside the exe hides the bundled one."""
    by_name = {}
    for d in reversed(template_dirs()):
        for f in sorted(os.listdir(d)):
            if f.endswith((".tpl", ".arxml")):
                by_name[f] = os.path.join(d, f)
    return [by_name[k] for k in sorted(by_name)]


def resolve_template(template: Optional[str]) -> str:
    name = template or DEFAULT_TEMPLATE_NAME
    if os.path.isabs(name) or os.path.exists(name):
        return name
    for d in template_dirs():
        cand = os.path.join(d, name)
        if os.path.exists(cand):
            return cand
    return os.path.join(TEMPLATE_DIR, name)


def generate(prj: Project, template: Optional[str] = None) -> str:
    # the gate sits here rather than on the buttons, so that every route to an
    # ARXML - GUI, CLI, bootstrap - passes through it
    licensing.require("generate ARXML")
    path = resolve_template(template)
    context = view_model.build(prj)
    header = ("<!--Autosar Release %s-->\n"
              "<!--Generated by the SOME/IP Config Tool from %s-->\n"
              % (prj.autosar_release, os.path.basename(path)))
    text = Renderer().render_file(path, context)
    # keep the generated-by note right after the XML declaration
    decl, _, rest = text.partition("\n")
    return decl + "\n" + header + rest


def write(prj: Project, out_path: str, template: Optional[str] = None) -> None:
    # render before opening: otherwise a licence refusal, or any template error,
    # would already have truncated whatever was there
    text = generate(prj, template)
    with open(out_path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(text)
