"""Generate the DaVinci Classic import ARXML.

There is deliberately no XML in this module.  The structure of the file - which
AUTOSAR elements exist and how they nest - lives in `templates/someip.arxml.tpl`;
the values come from `view_model.build()`.  To change the shape of the output,
edit the template, not this file.

    from arxml_gen import generate, write
    write(project, "ZA_someip.arxml")                       # default template
    write(project, "out.arxml", template="my_variant.tpl")  # another one
"""

from __future__ import annotations

import os
from typing import Optional

import view_model
from someip_model import Project
from template_engine import Renderer, TemplateError  # noqa: F401 - re-exported

TEMPLATE_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "templates")
DEFAULT_TEMPLATE = os.path.join(TEMPLATE_DIR, "someip.arxml.tpl")


def available_templates() -> list:
    if not os.path.isdir(TEMPLATE_DIR):
        return []
    return sorted(os.path.join(TEMPLATE_DIR, f) for f in os.listdir(TEMPLATE_DIR)
                  if f.endswith((".tpl", ".arxml")))


def resolve_template(template: Optional[str]) -> str:
    if not template:
        return DEFAULT_TEMPLATE
    if os.path.isabs(template) or os.path.exists(template):
        return template
    return os.path.join(TEMPLATE_DIR, template)


def generate(prj: Project, template: Optional[str] = None) -> str:
    path = resolve_template(template)
    context = view_model.build(prj)
    header = ("<!--Autosar Release %s-->\n"
              "<!--Generated by the SOME/IP Config Tool from %s-->\n"
              % (prj.autosar_release, os.path.basename(path)))
    text = Renderer().render_file(path, context)
    # keep the generated-by note right after the XML declaration
    decl, _, rest = text.partition("\n")
    return decl + "\n" + header + rest


def write(prj: Project, out_path: str, template: Optional[str] = None) -> None:
    with open(out_path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(generate(prj, template))
