"""Generate the SWC ARXML - a file of its own, beside the SOME/IP one.

The SOME/IP file declares the port interfaces and the data types; this one
declares an APPLICATION-SW-COMPONENT-TYPE whose ports point at them.  Nothing
here touches `arxml_gen`: the two generators share only the model, so a change
to the SWC cannot alter the SOME/IP output.

    from swc_gen import write
    write(project, "ZAFL_SoIpSwc.arxml")

Import order in DaVinci matters - the SOME/IP file first, this one second,
because every port here is a reference into that file.
"""

from __future__ import annotations

import os
from typing import Optional

import arxml_gen
import licensing
import view_model
from someip_model import Project
from template_engine import Renderer

DEFAULT_TEMPLATE_NAME = "swc.arxml.tpl"


def resolve_template(template: Optional[str]) -> str:
    """Same search path as the SOME/IP template: beside the exe, then bundled."""
    return arxml_gen.resolve_template(template or DEFAULT_TEMPLATE_NAME)


def generate(prj: Project, template: Optional[str] = None) -> str:
    # the gate sits here rather than on the button, so every route to a
    # generated file passes through it
    licensing.require("generate the SWC ARXML")
    path = resolve_template(template)
    context = view_model.build_swc(prj)
    header = ("<!--Autosar Release %s-->\n"
              "<!--SWC generated by the SOME/IP Config Tool from %s-->\n"
              "<!--Import the SOME/IP file first: every port refers to it-->\n"
              % (prj.autosar_release, os.path.basename(path)))
    text = Renderer().render_file(path, context)
    decl, _, rest = text.partition("\n")
    return decl + "\n" + header + rest


def write(prj: Project, out_path: str, template: Optional[str] = None) -> None:
    # render before opening, so a licence refusal or a template error cannot
    # truncate whatever was there
    text = generate(prj, template)
    with open(out_path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(text)


def default_file_name(prj: Project) -> str:
    return (prj.swc_name or (prj.ecu_name + "_SoIpSwc")) + ".arxml"
